apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: fola
  name: fola
  namespace: adeola-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fola
  strategy: {}
  template:
    metadata:
      labels:
        app: fola
    spec:
      containers:
      - image: IMAGE_NAME
        name: fola
        ports: 
        - containerPort: 80
        resources: {}
status: {}
